export * as authServices from './auth/authServices'
export * as menuServices from './menu/menuServices'
export * as tableServices from "./table/tableServices"
export * as restaurantServices from './restaurant/restaurantServices'
export * as shiftFundServices from './shift_fund/shift_fundServices'
export * as orderServices from './order/orderServices'
export * as orderDetailServices from './order/orderDetailServices'
export * as staffInfoServices from './staff/staffInforServices'
export * as purchaseServices from './ingredients/ingredientsServices'