export const months = {
    en: [
      { value: "01", label: "January" },
      { value: "02", label: "February" },
      { value: "03", label: "March" },
      { value: "04", label: "April" },
      { value: "05", label: "May" },
      { value: "06", label: "June" },
      { value: "07", label: "July" },
      { value: "08", label: "August" },
      { value: "09", label: "September" },
      { value: "10", label: "October" },
      { value: "11", label: "November" },
      { value: "12", label: "December" },
    ],
    vi: [
      { value: "01", label: "Tháng 1" },
      { value: "02", label: "Tháng 2" },
      { value: "03", label: "Tháng 3" },
      { value: "04", label: "Tháng 4" },
      { value: "05", label: "Tháng 5" },
      { value: "06", label: "Tháng 6" },
      { value: "07", label: "Tháng 7" },
      { value: "08", label: "Tháng 8" },
      { value: "09", label: "Tháng 9" },
      { value: "10", label: "Tháng 10" },
      { value: "11", label: "Tháng 11" },
      { value: "12", label: "Tháng 12" },
    ],
  };
  